{
 "title": "MONTAÑA RUSA",
 "time": { "from": "2026-04-13T00:16:59.974Z", "to": "2026-04-19T13:35:25.342Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "VAGON 1",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "ACELERACION EJE DELANTERO",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
     "targets": [
      {
       "query": "from(bucket: \"Montaña_Rusa\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._measurement == \"sensores\")\r\n  |> filter(fn: (r) => r._field == \"aceleracion\")\r\n  |> filter(fn: (r) => r.sensor_id == \"Vagon_1_Eje_delantero\")\r\n"
      }
     ]
    },
    {
     "title": "ACELERACION EJE TRASERO",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
     "targets": [
      {
       "query": "from(bucket: \"Montaña_Rusa\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._measurement == \"sensores\")\r\n  |> filter(fn: (r) => r._field == \"aceleracion\")\r\n  |> filter(fn: (r) => r.sensor_id == \"Vagon_1_Eje_trasero\")\r\n"
      }
     ]
    },
    {
     "title": "VIBRACION EJE DELANTERO",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
     "targets": [
      {
       "query": "from(bucket: \"Montaña_Rusa\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._measurement == \"sensores\")\r\n  |> filter(fn: (r) => r._field == \"vibracion\")\r\n  |> filter(fn: (r) => r.sensor_id == \"Vagon_1_Eje_delantero\")\r\n"
      }
     ]
    },
    {
     "title": "VIBRACION EJE TRASERO",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
     "targets": [
      {
       "query": "from(bucket: \"Montaña_Rusa\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._measurement == \"sensores\")\r\n  |> filter(fn: (r) => r._field == \"vibracion\")\r\n  |> filter(fn: (r) => r.sensor_id == \"Vagon_1_Eje_trasero\")\r\n"
      }
     ]
    },
    {
     "title": "ACELERACION EJE DELANTERO",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 178 },
     "targets": [
      {
       "query": "from(bucket: \"Montaña_Rusa\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._measurement == \"sensores\")\r\n  |> filter(fn: (r) => r._field == \"aceleracion\")\r\n  |> filter(fn: (r) => r.sensor_id == \"Vagon_1_Eje_delantero\")\r\n"
      }
     ]
    },
    {
     "title": "ACELERACION EJE TRASERO",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 178 },
     "targets": [
      {
       "query": "from(bucket: \"Montaña_Rusa\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._measurement == \"sensores\")\r\n  |> filter(fn: (r) => r._field == \"aceleracion\")\r\n  |> filter(fn: (r) => r.sensor_id == \"Vagon_1_Eje_trasero\")\r\n"
      }
     ]
    },
    { "title": "ALERTAS", "type": "alertlist", "gridPos": { "h": 9, "w": 12, "x": 12, "y": 178 } }
   ]
  },
  {
   "title": "VAGON 2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "ACELERACION EJE DELANTERO",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 2 },
     "targets": [
      {
       "query": "from(bucket: \"Montaña_Rusa\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._measurement == \"sensores\")\r\n  |> filter(fn: (r) => r._field == \"aceleracion\")\r\n  |> filter(fn: (r) => r.sensor_id == \"Vagon_2_Eje_delantero\")\r\n"
      }
     ]
    },
    {
     "title": "ACELERACION EJE TRASERO",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 2 },
     "targets": [
      {
       "query": "from(bucket: \"Montaña_Rusa\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._measurement == \"sensores\")\r\n  |> filter(fn: (r) => r._field == \"aceleracion\")\r\n  |> filter(fn: (r) => r.sensor_id == \"Vagon_2_Eje_trasero\")\r\n"
      }
     ]
    },
    {
     "title": "VIBRACION EJE DELANTERO",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 2 },
     "targets": [
      {
       "query": "from(bucket: \"Montaña_Rusa\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._measurement == \"sensores\")\r\n  |> filter(fn: (r) => r._field == \"vibracion\")\r\n  |> filter(fn: (r) => r.sensor_id == \"Vagon_2_Eje_delantero\")\r\n"
      }
     ]
    },
    {
     "title": "VIBRACION EJE TRASERO",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 2 },
     "targets": [
      {
       "query": "from(bucket: \"Montaña_Rusa\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._measurement == \"sensores\")\r\n  |> filter(fn: (r) => r._field == \"vibracion\")\r\n  |> filter(fn: (r) => r.sensor_id == \"Vagon_2_Eje_trasero\")\r\n"
      }
     ]
    },
    {
     "title": "TEMPERATURA EJE DELANTERO",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 29 },
     "targets": [
      {
       "query": "from(bucket: \"Montaña_Rusa\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._measurement == \"sensores\")\r\n  |> filter(fn: (r) => r._field == \"temperatura\")\r\n  |> filter(fn: (r) => r.sensor_id == \"Vagon_2_Eje_delantero\")\r\n"
      }
     ]
    },
    {
     "title": "TEMPERATURA EJE TRASERO",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 29 },
     "targets": [
      {
       "query": "from(bucket: \"Montaña_Rusa\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._measurement == \"sensores\")\r\n  |> filter(fn: (r) => r._field == \"temperatura\")\r\n  |> filter(fn: (r) => r.sensor_id == \"Vagon_2_Eje_trasero\")\r\n"
      }
     ]
    },
    { "title": "ALERTAS", "type": "alertlist", "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 } }
   ]
  },
  {
   "title": "VAGON 3",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "ACELERACION EJE DELANTERO",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 3 },
     "targets": [
      {
       "query": "from(bucket: \"Montaña_Rusa\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._measurement == \"sensores\")\r\n  |> filter(fn: (r) => r._field == \"aceleracion\")\r\n  |> filter(fn: (r) => r.sensor_id == \"Vagon_3_Eje_delantero\")\r\n"
      }
     ]
    },
    {
     "title": "ACELERACION EJE TRASERO",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 3 },
     "targets": [
      {
       "query": "from(bucket: \"Montaña_Rusa\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._measurement == \"sensores\")\r\n  |> filter(fn: (r) => r._field == \"aceleracion\")\r\n  |> filter(fn: (r) => r.sensor_id == \"Vagon_3_Eje_trasero\")\r\n"
      }
     ]
    },
    {
     "title": "VIBRACION EJE DELANTERO",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 3 },
     "targets": [
      {
       "query": "from(bucket: \"Montaña_Rusa\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._measurement == \"sensores\")\r\n  |> filter(fn: (r) => r._field == \"vibracion\")\r\n  |> filter(fn: (r) => r.sensor_id == \"Vagon_3_Eje_delantero\")\r\n"
      }
     ]
    },
    {
     "title": "VIBRACION EJE TRASERO",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 3 },
     "targets": [
      {
       "query": "from(bucket: \"Montaña_Rusa\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._measurement == \"sensores\")\r\n  |> filter(fn: (r) => r._field == \"vibracion\")\r\n  |> filter(fn: (r) => r.sensor_id == \"Vagon_3_Eje_trasero\")\r\n"
      }
     ]
    },
    {
     "title": "TEMPERATURA EJE DELANTERO",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 12 },
     "targets": [
      {
       "query": "from(bucket: \"Montaña_Rusa\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._measurement == \"sensores\")\r\n  |> filter(fn: (r) => r._field == \"temperatura\")\r\n  |> filter(fn: (r) => r.sensor_id == \"Vagon_3_Eje_delantero\")\r\n"
      }
     ]
    },
    {
     "title": "TEMPERATURA EJE TRASERO",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 12 },
     "targets": [
      {
       "query": "from(bucket: \"Montaña_Rusa\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._measurement == \"sensores\")\r\n  |> filter(fn: (r) => r._field == \"temperatura\")\r\n  |> filter(fn: (r) => r.sensor_id == \"Vagon_3_Eje_trasero\")\r\n"
      }
     ]
    },
    { "title": "ALERTAS", "type": "alertlist", "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 } }
   ]
  },
  {
   "title": "VAGON 4",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "ACELERACION EJE DELANTERO",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 4 },
     "targets": [
      {
       "query": "from(bucket: \"Montaña_Rusa\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._measurement == \"sensores\")\r\n  |> filter(fn: (r) => r._field == \"aceleracion\")\r\n  |> filter(fn: (r) => r.sensor_id == \"Vagon_4_Eje_delantero\")\r\n"
      }
     ]
    },
    {
     "title": "ACELERACION EJE TRASERO",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 4 },
     "targets": [
      {
       "query": "from(bucket: \"Montaña_Rusa\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._measurement == \"sensores\")\r\n  |> filter(fn: (r) => r._field == \"aceleracion\")\r\n  |> filter(fn: (r) => r.sensor_id == \"Vagon_4_Eje_trasero\")\r\n"
      }
     ]
    },
    {
     "title": "VIBRACION EJE DELANTERO",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 4 },
     "targets": [
      {
       "query": "from(bucket: \"Montaña_Rusa\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._measurement == \"sensores\")\r\n  |> filter(fn: (r) => r._field == \"vibracion\")\r\n  |> filter(fn: (r) => r.sensor_id == \"Vagon_4_Eje_delantero\")\r\n"
      }
     ]
    },
    {
     "title": "VIBRACION EJE TRASERO",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 4 },
     "targets": [
      {
       "query": "from(bucket: \"Montaña_Rusa\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._measurement == \"sensores\")\r\n  |> filter(fn: (r) => r._field == \"vibracion\")\r\n  |> filter(fn: (r) => r.sensor_id == \"Vagon_4_Eje_trasero\")\r\n"
      }
     ]
    },
    {
     "title": "TEMPERATURA EJE DELANTERO",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 13 },
     "targets": [
      {
       "query": "from(bucket: \"Montaña_Rusa\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._measurement == \"sensores\")\r\n  |> filter(fn: (r) => r._field == \"temperatura\")\r\n  |> filter(fn: (r) => r.sensor_id == \"Vagon_4_Eje_delantero\")\r\n"
      }
     ]
    },
    {
     "title": "TEMPERATURA EJE TRASERO",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 13 },
     "targets": [
      {
       "query": "from(bucket: \"Montaña_Rusa\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._measurement == \"sensores\")\r\n  |> filter(fn: (r) => r._field == \"temperatura\")\r\n  |> filter(fn: (r) => r.sensor_id == \"Vagon_4_Eje_trasero\")\r\n"
      }
     ]
    },
    { "title": "ALERTAS", "type": "alertlist", "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 } }
   ]
  }
 ]
}