sonar.projectKey=SDLC_parque
sonar.organization=alaiayeregui

# Ruta al código fuente
sonar.sources=backend
sonar.python.version=3.10

# Rutas a los tests (para que no los cuente como código de producción)
sonar.tests=backend/test
sonar.python.xunit.reportPath=test-reports/results.xml